lsi: false
safe: true
source: [M5-Forecasting-Accuracy]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-cayman